version: "3.0"
services:
  redis-dev:
   image: redis:7.0.7
   container_name: redis-dev
   ports:
     - 6379:6379
   restart: always
   volumes:
     - ./vol-redis:/data
   networks:
     - backend
networks:
  backend:
    driver: bridge
