version: "3.0"
services:
  redis-test:
   image: redis:7.0.7
   container_name: redis-test
   command: --port 6378
   ports:
     - 6378:6378
   restart: always
   volumes:
     - ./vol-redis:/data
   networks:
     - backend-test
networks:
  backend-test:
    driver: bridge
