alter table dbo.USUARIO ADD COLUMN USUARIO_EXCLUSAO_ID INT;
alter table dbo.USUARIO ADD COLUMN DATA_EXCLUSAO TIMESTAMP;
alter table dbo.USUARIO ADD COLUMN EXCLUIDO BIT;

ALTER TABLE dbo.USUARIO ADD FOREIGN KEY (USUARIO_EXCLUSAO_ID) REFERENCES dbo.USUARIO(ID);