create schema if not exists dbo;

create table dbo.PERFIL(
    ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    CONSTRAINT PERFIL_PK PRIMARY KEY(ID)
);

CREATE SEQUENCE dbo.PERFIL_SEQUENCE_ID
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1;

ALTER TABLE dbo.PERFIL ALTER COLUMN ID SET DEFAULT NEXTVAL('dbo.PERFIL_SEQUENCE_ID'::regclass);

create table dbo.USUARIO(
    ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SALDO_TOTAL NUMERIC DEFAULT 0,
    CONSTRAINT USUARIO_PK PRIMARY KEY(ID)
);

CREATE SEQUENCE dbo.USUARIO_SEQUENCE_ID
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1;

ALTER TABLE dbo.USUARIO ALTER COLUMN ID SET DEFAULT NEXTVAL('dbo.USUARIO_SEQUENCE_ID'::regclass);

create table dbo.USUARIOS_PERFIL(
    USUARIO_ID INT NOT NULL,
    PERFIL_ID INT NOT NULL
);

ALTER TABLE dbo.USUARIOS_PERFIL ADD FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIO(ID);
ALTER TABLE dbo.USUARIOS_PERFIL ADD FOREIGN KEY (PERFIL_ID) REFERENCES dbo.PERFIL(ID);

create table dbo.SAQUE(
    ID INT NOT NULL,
    VALOR NUMERIC NOT NULL,
    DATA_SAQUE TIMESTAMP NOT NULL,
    USUARIO_ID INT NOT NULL,
    CONSTRAINT SAQUE_PK PRIMARY KEY(ID)
);

CREATE SEQUENCE dbo.SAQUE_SEQUENCE_ID
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1;

ALTER TABLE dbo.SAQUE ALTER COLUMN ID SET DEFAULT NEXTVAL('dbo.SAQUE_SEQUENCE_ID'::regclass);

ALTER TABLE dbo.SAQUE ADD FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIO(ID);

create table dbo.SALDO(
    ID INT NOT NULL,
    DEPOSITO NUMERIC NOT NULL,
    DATA_DEPOSITO TIMESTAMP NOT NULL,
    USUARIO_ID INT NOT NULL,
    CONSTRAINT SALDO_PK PRIMARY KEY(ID)
);

CREATE SEQUENCE dbo.SALDO_SEQUENCE_ID
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1;

ALTER TABLE dbo.SALDO ALTER COLUMN ID SET DEFAULT NEXTVAL('dbo.SALDO_SEQUENCE_ID'::regclass);

ALTER TABLE dbo.SALDO ADD FOREIGN KEY (USUARIO_ID) REFERENCES dbo.USUARIO(ID);