create schema if not exists dbo;

create table dbo.SITUACAO(
    ID INT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    CODIGO VARCHAR(255) NOT NULL,
    CONSTRAINT SITUACAO_PK PRIMARY KEY(ID)
);

CREATE SEQUENCE dbo.SITUACAO_SEQUENCE_ID
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1;

ALTER TABLE dbo.SITUACAO ALTER COLUMN ID SET DEFAULT NEXTVAL('dbo.SITUACAO_SEQUENCE_ID'::regclass);