ALTER TABLE dbo.USUARIO_MOVIMENTACAO ADD SALDO_ID INT;
ALTER TABLE dbo.USUARIO_MOVIMENTACAO ADD SAQUE_ID INT;
ALTER TABLE dbo.USUARIO_MOVIMENTACAO ADD FOREIGN KEY (SALDO_ID) REFERENCES dbo.SALDO(ID);
ALTER TABLE dbo.USUARIO_MOVIMENTACAO ADD FOREIGN KEY (SAQUE_ID) REFERENCES dbo.SAQUE(ID);