alter table dbo.USUARIO ADD COLUMN USUARIO_INCLUSAO_ID INT;
alter table dbo.USUARIO ADD COLUMN DATA_INCLUSAO TIMESTAMP;
alter table dbo.USUARIO ADD COLUMN USUARIO_ALTERACAO_ID INT;
alter table dbo.USUARIO ADD COLUMN DATA_ALTERACAO TIMESTAMP;

ALTER TABLE dbo.USUARIO ADD FOREIGN KEY (USUARIO_INCLUSAO_ID) REFERENCES dbo.USUARIO(ID);
ALTER TABLE dbo.USUARIO ADD FOREIGN KEY (USUARIO_ALTERACAO_ID) REFERENCES dbo.USUARIO(ID);